name: Deployment_Lab3

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout depot
        uses: actions/checkout@v4

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASSWORD=labo03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Cleanup complet
        run: |
          docker compose down -v --remove-orphans || true
          docker network rm labo03-network 2>/dev/null || true
          docker rm -f mysql redis store_manager 2>/dev/null || true
          docker system prune -f --volumes #Nettoyage aggressif, mesure de last resort
          
      - name: Demarrer les services
        run: |
          docker network create labo03-network || true
          docker compose up -d --build

      - name: Wait MySQL
        run: |
          timeout=60
          until [ "$(docker ps -a -q -f name=mysql)" ]; do
            echo "Waiting for container 'mysql' to be created..."
            sleep 2
          done
          
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "MySQL is starting up..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start within timeout"
              docker logs mysql
              exit 1
            fi
          done

      - name: Attendre que les tables soient prêtes
        run: |
          timeout=60
          until docker exec mysql mysql -ulabo03 -plabo03 labo03_db -e "SELECT 1 FROM users LIMIT 1;" >/dev/null 2>&1; do
            echo "MySQL est debout, mais j'attends la création des tables..."
            sleep 2
            timeout=$((timeout - 2))
            if [ $timeout -le 0 ]; then exit 1; fi
          done
          echo "Tables prêtes, lancement des tests !"
        
      - name: Executer les tests de validation
        run: docker exec store_manager pytest src/tests

      - name: Status
        if: success()
        run: echo "Labo 03 déployé et testé sur la VM"