name: Deployment_Lab3

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout depot
        uses: actions/checkout@v4

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASSWORD=labo03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Cleanup complet
        run: |
          docker compose down -v --remove-orphans || true
          docker network rm labo03-network 2>/dev/null || true
          docker rm -f mysql redis store_manager 2>/dev/null || true
          
      - name: Demarrer les services
        run: |
          docker network create labo03-network || true
          docker compose up -d --build

      - name: Attendre MySQL (Sant√© de la DB)
        run: |
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then exit 1; fi
          done
          sleep 5 # Laisser le temps aux scripts d'init .sql de finir
        
      - name: Executer les tests de validation
        run: docker exec store_manager pytest

      - name: Status
        if: success()
        run: echo "üöÄ Labo 03 d√©ploy√© et test√© sur la VM!"